export default [
    'sponsor-ayakkabi',
    'sponsor-product',
    'sponsor-product-1',
    'sponsor-product-2',//koton
    'sponsor-product-3',//mango
    'sponsor-product-4',//beymen
    'sponsor-product-5',//hmdtektil
    'sponsor-product-6',//matras
    'sponsor-product-7',//ateliergalin
    'sponsor-product-8',//diesel
    'sponsor-product-9',//uspoloassn
    'sponsor-product-10',//gap
    'sponsor-product-11',//burberry
    'sponsor-product-13',//camper
    'sponsor-product-14',//converse
    'sponsor-product-15',//eclecticconceptstore
    'sponsor-product-17',//gant
    'sponsor-product-18',//lacoste
    'sponsor-product-19',//pierrecardin
    'sponsor-product-24',//morrez 
    'sponsor-product-25',//yaygan
    'sponsor-product-M-4',//mudo
    'sponsor-product-M-5',//muun
    'sponsor-product-M-6'//sagaza 
    ]